apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: ${releaseNamespace}
  labels:
    app: vllm
spec:
  selector:
    app: vllm
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP