apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: llm-llm-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      storage: nfs
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: llm-volume