apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: llm-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: llm-llm-claim
  nfs:
    path: /llm-model-store
    server: files.romanticism.cloudnative.nvdlab.net
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem