---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  interval: 1m0s
  ref:
    tag: v1.10.0
  timeout: 15m0s
  url: https://github.com/kubeflow/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  wait: true
  retryInterval: 5m
  patches:
  - patch: |
      $patch: delete 
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: kfp-launcher
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: mlpipeline-minio-artifact
  - patch: |
      $patch: delete 
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: minio
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: minio-service
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minio-pvc
  - patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
  - patch: |
     - op: add
       path: /metadata/namespace
       value: default
    target:
      kind: ConfigMap
      name: default-install-config.*
  - patch: | 
      apiVersion: networking.istio.io/v1beta1
      kind: Gateway
      metadata:
        name: kubeflow-gateway
      spec:
        servers:
        - hosts:
          - '*'
          port:
            name: http
            number: 80
            protocol: HTTP
        - hosts:
          - '*'
          port:
            name: https
            number: 443
            protocol: HTTPS
          tls:
            credentialName: kubeflow-tls
            mode: SIMPLE
    target:
      kind: Gateway
      name: kubeflow-gateway
      namespace: kubeflow
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ml-pipeline
      spec:
        template:
          spec:
            containers:
              - env:
                  - name: OBJECTSTORECONFIG_HOST
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config-ntnx
                        key: objStoreHost
                  - name: OBJECTSTORECONFIG_BUCKETNAME
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config-ntnx
                        key: bucketName
                  - name: OBJECTSTORECONFIG_REGION
                    valueFrom:
                      configMapKeyRef:
                        name: pipeline-install-config-ntnx
                        key: objStoreRegion
                  - name: OBJECTSTORECONFIG_PORT
                      configMapKeyRef:
                        name: pipeline-install-config-ntnx
                        key: objStorePort
                name: ml-pipeline-api-server
    target:
      kind: Deployment
      name: ml-pipeline
      namespace: kubeflow
  interval: 6h
  timeout: 15m0s
  path: ./example
  prune: false
  sourceRef:
   kind: GitRepository
   name: kubeflow-instance
   namespace: ${releaseNamespace}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubeflow-ntnx
  namespace: kommander-flux
spec:
  interval: 10m
  url: "${helmMirrorURL:=https://raw.githubusercontent.com/wolfganghuse/soleng-hackathon-july24/kubeflow-2025/kubeflow-ntnx-charts}"
---
# Note: The name of the release must match the services folder name for the overrides to work
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeflow
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubeflow-ntnx
      sourceRef:
        kind: HelmRepository
        name: kubeflow-ntnx
        namespace: kommander-flux
      version: 1.10.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: kubeflow-1.10.0-ntnx-defaults
  targetNamespace: ${releaseNamespace}
