---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flowise
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: flowise
      sourceRef:
        kind: HelmRepository
        name: cowboysysop.github.io/charts
        namespace: ${workspaceNamespace}
      version: 3.8.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: flowise
  valuesFrom:
    - kind: ConfigMap
      name: flowise-2.0.7-nkp-defaults
  targetNamespace: ${releaseNamespace}