# Hack to populate Object Store Details using Helm as pipeline-install-config is owned by the core kustomization and can't be
# deleted from there due to variabledependencies. See "apps/pipeline/upstream/base/installs/generic/kustomization.yaml" in the
# core kustomization repo
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: pipeline-install-config-ntnx
  namespace: kubeflow
data:
  objStoreHost: {{ .Values.objStoreHost }}
  bucketName: {{ .Values.bucket }}
  objStoreRegion: {{ .Values.objStoreRegion }}
  insecure: {{ .Values.disableSSL }}