apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${releaseName}-instance
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
  path: ./services/vllm/0.5.2/manifests
  sourceRef:
    kind: GitRepository
    name: soleng-catalog
    namespace: kommander
  timeout: 1m
  # passing releaseNamespace to 2nd level configuration files for ability to configure namespace correctly in attached clusters
  # Using `substituteFrom` with `substitution-vars` creates 2nd level resources in `kommander` namespace instead of workspace ns
  postBuild:
    substitute:
      releaseNamespace: ${releaseNamespace}