# Default values for kubeflow-ntnx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
kubeflowIngressIP: 10.124.254.228
objStoreHost: objects.solengcnai-lab.cloudnative.nvdlab.net
bucket: mlpipeline-wolfgang
accesskey: 2_E2scE2hit4p2LdbgXA5tzptA4g-Utk
secretkey: DzOwbItwTrt1so91BcltVo1Ef-e9xIYP
objStoreRegion: us-east-1
disableSSL: true